import { DataTypes } from "sequelize";
const Types = {
    "ABSTRACT": DataTypes.ABSTRACT,
    "ARRAY": DataTypes.ARRAY,
    "BIGINT": DataTypes.BIGINT,
    "BLOB": DataTypes.BLOB,
    "BOOLEAN": DataTypes.BOOLEAN,
    "CHAR": DataTypes.CHAR,
    "CIDR": DataTypes.CIDR,
    "CITEXT": DataTypes.CITEXT,
    "DATE": DataTypes.DATE,
    "DATEONLY": DataTypes.DATEONLY,
    "DECIMAL": DataTypes.DECIMAL,
    "DOUBLE": DataTypes.DOUBLE,
    "ENUM": DataTypes.ENUM,
    "FLOAT": DataTypes.FLOAT,
    "GEOGRAPHY": DataTypes.GEOGRAPHY,
    "GEOMETRY": DataTypes.GEOMETRY,
    "HSTORE": DataTypes.HSTORE,
    "INET": DataTypes.INET,
    "INTEGER": DataTypes.INTEGER,
    "JSON": DataTypes.JSON,
    "JSONB": DataTypes.JSONB,
    "MACADDR": DataTypes.MACADDR,
    "MEDIUMINT": DataTypes.MEDIUMINT,
    "NOW": DataTypes.NOW,
    "NUMBER": DataTypes.NUMBER,
    "RANGE": DataTypes.RANGE,
    "REAL": DataTypes.REAL,
    "SMALLINT": DataTypes.SMALLINT,
    "STRING": DataTypes.STRING,
    "TEXT": DataTypes.TEXT,
    "TIME": DataTypes.TIME,
    "TINYINT": DataTypes.TINYINT,
    "TSVECTOR": DataTypes.TSVECTOR,
    "UUID": DataTypes.UUID,
    "UUIDV1": DataTypes.UUIDV1,
    "UUIDV4": DataTypes.UUIDV4,
    "VIRTUAL": DataTypes.VIRTUAL,
};
export default Types;
